title: Oinam Art
description: Artistic redention of fun, family, and friends.

remote_theme: oinam/oinam-jekyll
markdown: kramdown
permalink: pretty
permalink: /:year/:title/
future: false
show_drafts: false

footer:
  credit: false
  custom: false

layout:
  theme: default

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - README.*
  - vendor/